#!/usr/bin/env bash
set -euo pipefail

source "$HOME/miniconda3/etc/profile.d/conda.sh"
conda activate habitat

DATA_PATH="$HOME/embodied_ai/data"
mkdir -p "$DATA_PATH"

# Clean only the partial data directories generated by failed Habitat downloads.
rm -rf \
  "$DATA_PATH/versioned_data/habitat_test_scenes" \
  "$DATA_PATH/scene_datasets/habitat-test-scenes" \
  "$DATA_PATH/versioned_data/habitat_example_objects" \
  "$DATA_PATH/objects/example_objects"

python -m habitat_sim.utils.datasets_download \
  --uids habitat_test_scenes \
  --data-path "$DATA_PATH/"

python -m habitat_sim.utils.datasets_download \
  --uids habitat_example_objects \
  --data-path "$DATA_PATH/"
